apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moazrefat/argocd.git
    targetRevision: HEAD
    path: core
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    # server: https://192.168.178.110:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true