apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employees-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.moaaznoaman.com/root/argocd.git
    targetRevision: HEAD
    path: core/employees-prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: employees-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true