apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employees-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moazrefat/argocd.git
    targetRevision: HEAD
    path: core/employees-prod
    directory:
      recurse: true
  destination:
    # server: https://kubernetes.default.svc
    server: https://192.168.178.110:6443  
    namespace: employees-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true