apiVersion: v1
kind: Namespace
metadata:
  name: employees-dev
---
apiVersion: v1
data:
  APP_ENVIRONMENT: production
  DEBUG_METRICS: "false"
  MYSQL_DATABASE: app
  MYSQL_LB: db-service
  MYSQL_PASSWORD: dontplaywithme
  MYSQL_ROOT_PASSWORD: dontplaywithme
  MYSQL_USER: admin
  VERSION_SERVICE: version-svc
kind: ConfigMap
metadata:
  labels:
    app: employees
  name: emp-config
  namespace: employees-dev
---
apiVersion: v1
data:
  MYSQL_DATABASE: app
  MYSQL_PASSWORD: dontplaywithme
  MYSQL_ROOT_PASSWORD: dontplaywithme
  MYSQL_USER: admin
kind: ConfigMap
metadata:
  labels:
    app: mysql-db
  name: mysql-config
  namespace: employees-dev
---
apiVersion: v1
data:
  MYSQL_DATABASE: version
  MYSQL_LB: db-service
  MYSQL_PASSWORD: dontplaywithme
  MYSQL_ROOT_PASSWORD: dontplaywithme
  MYSQL_USER: admin
kind: ConfigMap
metadata:
  labels:
    app: version
  name: version-config
  namespace: employees-dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: db
    tier: back
  name: db-service
  namespace: employees-dev
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employees
  name: employees-lb
  namespace: employees-dev
spec:
  ports:
  - name: emp-port
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: employees
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: version
    service: version
  name: version-svc
  namespace: employees-dev
spec:
  ports:
  - port: 8080
  selector:
    app: version
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employees
    version: v1
  name: employees
  namespace: employees-dev
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: employees
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: emp-config
        image: moazrefat/employees:dev
        imagePullPolicy: Always
        name: employees
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: employees-dev
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
      tier: back
  template:
    metadata:
      labels:
        app: mysql-db
        role: db
        tier: back
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mysql-config
        image: moazrefat/employees:db-dev
        imagePullPolicy: Always
        name: mysql-db
        ports:
        - containerPort: 3306
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: version
    version: v1
  name: version-v1
  namespace: employees-dev
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: version
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: version
        version: v1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: version-config
        image: moazrefat/version:dev
        imagePullPolicy: Always
        name: version
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: moaaznoaman
# spec:
#   acme:
#     email: moazrefatg@gmail.com
#     privateKeySecretRef:
#       name: moaaznoaman
#     server: https://acme-v02.api.letsencrypt.org/directory
#     solvers:
#     - http01:
#         ingress:
#           class: nginx
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     cert-manager.io/cluster-issuer: moaaznoaman
#     kubernetes.io/ingress.class: nginx
#   labels:
#     app: employees
#   name: employees-ingress-dev
#   namespace: employees-dev
# spec:
#   rules:
#   - host: dev.k8s.moaaznoaman.com
#     http:
#       paths:
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /api/hostname
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /api/details
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /api/register
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /api/health
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /api/info
#       - backend:
#           serviceName: employees-lb
#           servicePort: 8080
#         path: /metrics
#   tls:
#   - hosts:
#     - dev.k8s.moaaznoaman.com
#     secretName: employees-dev
